/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;


/**
 *
 * @author alexiaidrac
 */
public class Acte extends javax.swing.JFrame {

    private DossierMedicalRadiologie dmr;
    private BufferedImage currentImage;
    private BufferedImage modifiedImage;
    private BufferedImage invertedImage;
    private BufferedImage flippedImage;
    private BufferedImage currentImageFromDB;
    private byte[] imageData;
    BufferedImage imageFromDB;

    private int rotationAngle = 0; // Variable pour suivre l'angle de rotation
    private double contraste = 0.25; //variable contraste de base

    private DefaultTableModel model;
    private int idacte;
    private int idPatient;
    Connection conn;

    /**
     * Creates new form DMR
     */
    public Acte(DossierMedicalRadiologie dmr, int idacte, String codeActe, String nomPracticien, Date dateActe, double tarification, String acte, byte[] imageData) {
        initComponents();
        this.idPatient = dmr.getIdPatient();
        this.dmr = dmr;
        this.acte.setText(acte);

        jButtonIncreaseContraste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncreaseContrasteActionPerformed(evt);
                jButtonDecreaseContrastActionPerformed(evt);
                jButtonRestartContrastActionPerformed(evt);
                jButtonFlipHActionPerformed(evt);
                jButtonFlipVActionPerformed(evt);
            }
        });
        System.out.println("interface Acte");
        String idActe = String.valueOf(idacte);
        infoID.setText(String.valueOf(this.idacte));
        System.out.println("idacte :" + idacte);
        String datedeActe = dateActe.toString();

        infoID.setText(idActe);
        infoCode.setText(codeActe);
        infoPrenom.setText(nomPracticien);
        infoDate.setText(datedeActe);
        infoAdresse.setText(String.valueOf(tarification));

// Afficher le compte rendu correspondant à l'IDCR dans jTextAreaCR
        int ID = idPatient; //recup l'id patient  
        String IDACTE = infoID.getText(); // Récupérer l'ID stocké dans infoID sara
        String idCR = String.valueOf(ID) + String.valueOf(IDACTE); // Concaténer l'ID et l'ID d'acte pour former idCR
        int idCRint = Integer.parseInt(idCR);//converti en int
        
        afficherCompteRendu(idCRint); // Appel de la méthode pour afficher le compte rendu
        this.acte.setText(acte);
        this.dmr = dmr;
        this.imageData = imageData;
        imageFromDB = loadImageFromBytes(imageData);

//        model = new DefaultTableModel(new Object[]{"IDACTE", "CODE ACTE", "TARIFICATION", "Date Acte", "PRATICIEN", "Signification du Code"}, 0);
//        jTextAreaCR.setModel(model); // Appliquer le modèle au jTextAreaCR
//        jTextAreaCR.setDefaultEditor(Object.class, null); // Rendre toutes les cellules non éditables
//        
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@im2ag-oracle.univ-grenoble-alpes.fr:1521:im2ag", "qezbourn", "d87b488b99");
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Acte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        ImageBrain = new javax.swing.JLabel();
        jButtonRotate90 = new javax.swing.JButton();
        jButtonIncreaseContraste = new javax.swing.JButton();
        jButtonDecreaseContrast = new javax.swing.JButton();
        jButtonRestartContrast = new javax.swing.JButton();
        jButtonInversionGris = new javax.swing.JButton();
        jButtonFlipH = new javax.swing.JButton();
        jButtonFlipV = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanelInfoActe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        infoID = new javax.swing.JLabel();
        infoCode = new javax.swing.JLabel();
        infoPrenom = new javax.swing.JLabel();
        infoDate = new javax.swing.JLabel();
        infoAdresse = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        acte = new javax.swing.JLabel();
        jButtonRetour = new javax.swing.JButton();
        jPanelCR = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCR = new javax.swing.JTextArea();
        jButtonEnregistrerCR = new javax.swing.JButton();
        jButtonImprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(173, 200, 213));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Radiographie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Galvji", 1, 14)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Galvji", 1, 13))); // NOI18N

        ImageBrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/brain1_0000.jpg"))); // NOI18N

        jButtonRotate90.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRotate90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/rafraichir.png"))); // NOI18N
        jButtonRotate90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRotate90ActionPerformed(evt);
            }
        });

        jButtonIncreaseContraste.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIncreaseContraste.setText("+");
        jButtonIncreaseContraste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncreaseContrasteActionPerformed(evt);
            }
        });

        jButtonDecreaseContrast.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDecreaseContrast.setText("-");
        jButtonDecreaseContrast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecreaseContrastActionPerformed(evt);
            }
        });

        jButtonRestartContrast.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRestartContrast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/reinitialiser.png"))); // NOI18N
        jButtonRestartContrast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestartContrastActionPerformed(evt);
            }
        });

        jButtonInversionGris.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInversionGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/echanger.png"))); // NOI18N
        jButtonInversionGris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInversionGrisActionPerformed(evt);
            }
        });

        jButtonFlipH.setBackground(new java.awt.Color(255, 255, 255));
        jButtonFlipH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/retournement-vertical.png"))); // NOI18N
        jButtonFlipH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlipHActionPerformed(evt);
            }
        });

        jButtonFlipV.setBackground(new java.awt.Color(255, 255, 255));
        jButtonFlipV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/retournement-horizontal.png"))); // NOI18N
        jButtonFlipV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlipVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRestartContrast, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonRotate90, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImageBrain)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonFlipH))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonInversionGris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRotate90, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jButtonIncreaseContraste)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDecreaseContrast))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonRestartContrast, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButtonFlipV)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(ImageBrain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonRotate90)
                        .addComponent(jButtonIncreaseContraste)
                        .addComponent(jButtonDecreaseContrast))
                    .addComponent(jButtonInversionGris)
                    .addComponent(jButtonFlipH)
                    .addComponent(jButtonFlipV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRestartContrast)
                .addGap(67, 67, 67))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examen Radiologique", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Galvji", 1, 18)))); // NOI18N

        jPanelInfoActe.setBackground(new java.awt.Color(173, 200, 213));
        jPanelInfoActe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations acte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Galvji", 1, 14)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Galvji", 2, 14)); // NOI18N
        jLabel1.setText("Numéro d'identification Acte :");

        jLabel2.setFont(new java.awt.Font("Galvji", 2, 14)); // NOI18N
        jLabel2.setText("Code Acte :");

        jLabel3.setFont(new java.awt.Font("Galvji", 2, 14)); // NOI18N
        jLabel3.setText("Nom Practicien");

        jLabel4.setFont(new java.awt.Font("Galvji", 2, 14)); // NOI18N
        jLabel4.setText("Date de l'acte :");

        jLabel5.setFont(new java.awt.Font("Galvji", 2, 14)); // NOI18N
        jLabel5.setText("Tarification :");

        infoID.setText("infoID");

        infoCode.setText("infoCode");

        infoPrenom.setText("infoNom");

        infoDate.setText("infoDate");

        infoAdresse.setText("infoTarification");

        jLabel6.setFont(new java.awt.Font("Galvji", 2, 14)); // NOI18N
        jLabel6.setText("Acte :");

        acte.setText("acte");

        javax.swing.GroupLayout jPanelInfoActeLayout = new javax.swing.GroupLayout(jPanelInfoActe);
        jPanelInfoActe.setLayout(jPanelInfoActeLayout);
        jPanelInfoActeLayout.setHorizontalGroup(
            jPanelInfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoActeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoActeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoID))
                    .addGroup(jPanelInfoActeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoCode))
                    .addGroup(jPanelInfoActeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoPrenom))
                    .addGroup(jPanelInfoActeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoDate))
                    .addGroup(jPanelInfoActeLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoAdresse))
                    .addGroup(jPanelInfoActeLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acte)))
        );
        jPanelInfoActeLayout.setVerticalGroup(
            jPanelInfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoActeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(infoID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(infoCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(acte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(infoPrenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(infoDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoActeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(infoAdresse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonRetour.setBackground(new java.awt.Color(76, 133, 160));
        jButtonRetour.setFont(new java.awt.Font("Galvji", 0, 13)); // NOI18N
        jButtonRetour.setText("Retour");
        jButtonRetour.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRetour.setBorderPainted(false);
        jButtonRetour.setMaximumSize(new java.awt.Dimension(57, 23));
        jButtonRetour.setMinimumSize(new java.awt.Dimension(57, 23));
        jButtonRetour.setPreferredSize(new java.awt.Dimension(57, 23));
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jPanelCR.setBackground(new java.awt.Color(173, 200, 213));
        jPanelCR.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compte rendu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Galvji", 1, 14)))); // NOI18N

        jTextAreaCR.setColumns(20);
        jTextAreaCR.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCR);

        jButtonEnregistrerCR.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEnregistrerCR.setFont(new java.awt.Font("Galvji", 0, 13)); // NOI18N
        jButtonEnregistrerCR.setText("Enregistrer");
        jButtonEnregistrerCR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEnregistrerCR.setBorderPainted(false);
        jButtonEnregistrerCR.setMaximumSize(new java.awt.Dimension(57, 23));
        jButtonEnregistrerCR.setMinimumSize(new java.awt.Dimension(57, 23));
        jButtonEnregistrerCR.setPreferredSize(new java.awt.Dimension(57, 23));
        jButtonEnregistrerCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerCRActionPerformed(evt);
            }
        });

        jButtonImprimer.setText("Imprimer");
        jButtonImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCRLayout = new javax.swing.GroupLayout(jPanelCR);
        jPanelCR.setLayout(jPanelCRLayout);
        jPanelCRLayout.setHorizontalGroup(
            jPanelCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addContainerGap(170, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCRLayout.setVerticalGroup(
            jPanelCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCRLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInfoActe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfoActe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCR, javax.swing.GroupLayout.PREFERRED_SIZE, 271, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        DossierMedicalRadiologie nouveauJFrame = dmr;
        nouveauJFrame.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jButtonEnregistrerCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerCRActionPerformed
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonEnregistrerCR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImprimer))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        // Créer des boutons personnalisés
        Object[] options = {"Valider", "Annuler"};
        System.out.println("texte CR: " + CONTENU + "-");
        System.out.println("idCR: " + idCRint + "-");

        // Afficher la boîte de dialogue avec les boutons personnalisés
        int choix = JOptionPane.showOptionDialog(
                null, // Parent component
                "Êtes-vous sûr de vouloir enregistrer le compte rendu ?", // Message
                "Confirmation", // Titre
                JOptionPane.YES_NO_CANCEL_OPTION, // Type de boîte de dialogue
                JOptionPane.QUESTION_MESSAGE, // Type d'icône
                null, // Icône personnalisée (null pour utiliser l'icône par défaut)
                options, // Boutons personnalisés
                options[0]); // Bouton par défaut

        // Gérer la réponse de l'utilisateur
        if (choix == JOptionPane.YES_OPTION) {
            try {
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnregistrerCR)
                    .addComponent(jButtonImprimer)))

                // Préparer la requête SQL pour insérer le compte rendu avec IDCR
                String sql = "INSERT INTO CR (IDCR, ID, CONTENU, IDACTE) VALUES (?, ?, ?, ?)";
                PreparedStatement statement = conn.prepareStatement(sql);
                statement.setInt(1, idCRint); // Remplace le premier paramètre (?) par la valeur de idCR
                statement.setInt(2, ID); // Remplace le deuxième paramètre (?) par la valeur de l'ID
                statement.setString(3, CONTENU); // Remplace le troisième paramètre (?) par la valeur du contenu
                statement.setInt(4, IDACTEint); // Remplace le quatrième paramètre (?) par la valeur de l'ID d'acte

                // Exécuter la requête SQL
                statement.executeUpdate();

                // Fermer la connexion
                conn.close();

                // Afficher un message de succès
                JOptionPane.showMessageDialog(null, "Compte rendu enregistré avec succès !");
            } catch (SQLException ex) {
                ex.printStackTrace();
                // Gérer les erreurs de connexion ou d'exécution de la requête
                JOptionPane.showMessageDialog(null, "Erreur lors de l'enregistrement du compte rendu : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }

        int ID = idPatient; //recup l'id patient  
        String CONTENU = jTextAreaCR.getText();// Récupérer le texte du jTextAreaCR
        String IDACTE = infoID.getText(); // Récupérer l'ID stocké dans infoID sara
        String idCR = String.valueOf(ID) + String.valueOf(IDACTE); // Concaténer l'ID et l'ID d'acte pour former idCR
        System.out.println("idacte : " + idacte + "-");
        System.out.println("IDACTE:" + IDACTE);
        //System.out.println("idActe:" + idActe);
        System.out.println("idpatient :" + idPatient + "-");
        int idCRint = Integer.parseInt(idCR);//converti en int
        int IDACTEint = Integer.parseInt(IDACTE);
        } else if (choix == JOptionPane.CANCEL_OPTION || choix == JOptionPane.CLOSED_OPTION) {
            // Action si l'utilisateur clique sur "Annuler" ou ferme la boîte de dialogue
            JOptionPane.getRootFrame().dispose();
        }
    }//GEN-LAST:event_jButtonEnregistrerCRActionPerformed

    private void jButtonRotate90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRotate90ActionPerformed
                // Établir la connexion à la base de données
                Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@im2ag-oracle.univ-grenoble-alpes.fr:1521:im2ag", "qezbourn", "d87b488b99");
            }
        } else {
            System.out.println("Aucune image chargée depuis la base de données.");
        }
    }//GEN-LAST:event_jButtonRotate90ActionPerformed

    private void jButtonIncreaseContrasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncreaseContrasteActionPerformed
        if (imageData != null) {
            BufferedImage imageFromDB = loadImageFromBytes(imageData);
            if (imageFromDB != null) {
                // Incrémentation du contraste
                contraste += 0.5; // Incrémente le contraste de 0.25 à chaque clic
                // Ajustement du contraste de l'image
                BufferedImage adjustedImage = adjustContrast(imageFromDB, contraste);
                // Mise à jour de l'image actuelle dans le JLabel
                applyProcessing(adjustedImage);
            } else {
                System.out.println("Impossible de charger l'image depuis la base de données.");
            }
        } else {
            System.out.println("Aucune image chargée depuis la base de données.");
        }
    }//GEN-LAST:event_jButtonIncreaseContrasteActionPerformed

    private void jButtonDecreaseContrastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecreaseContrastActionPerformed
        if (imageData != null) {
            BufferedImage imageFromDB = loadImageFromBytes(imageData);
            if (imageFromDB != null) {
                // Incrémentation du contraste
                contraste -= 0.5; // Incrémente le contraste de 0.25 à chaque clic
                // Ajustement du contraste de l'image
                BufferedImage adjustedImage = adjustContrast(imageFromDB, contraste);
                // Mise à jour de l'image actuelle dans le JLabel
                applyProcessing(adjustedImage);
            } else {
                System.out.println("Impossible de charger l'image depuis la base de données.");
            }
        } else {
            System.out.println("Aucune image chargée depuis la base de données.");
        }
    }//GEN-LAST:event_jButtonDecreaseContrastActionPerformed

    private void jButtonRestartContrastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestartContrastActionPerformed

        ImageBrain.setIcon(new ImageIcon(loadImageFromBytes(imageData))); // Restaurer l'image originale

    }//GEN-LAST:event_jButtonRestartContrastActionPerformed

    private void jButtonInversionGrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInversionGrisActionPerformed
        if (imageData != null) {
            //BufferedImage imageFromDB = loadImageFromBytes(imageData);
            if (imageFromDB != null) {
                // Appliquer l'inversion des niveaux de gris
                BufferedImage invertedImage = inversionNiveauGris(imageFromDB);
                // Mise à jour de l'image actuelle dans le JLabel
                applyProcessing(invertedImage);
                imageFromDB = invertedImage;
            } else {
                System.out.println("Impossible de charger l'image depuis la base de données.");
            }
        } else {
            System.out.println("Aucune image chargée depuis la base de données.");
        }
    }//GEN-LAST:event_jButtonInversionGrisActionPerformed

    private void jButtonFlipHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlipHActionPerformed
        flipHImage();
    }//GEN-LAST:event_jButtonFlipHActionPerformed

    private void jButtonFlipVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlipVActionPerformed
        flipVImage();
    }//GEN-LAST:event_jButtonFlipVActionPerformed

    private void jButtonImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimerActionPerformed

   PrinterJob imprimer = PrinterJob.getPrinterJob();
        if (imprimer.printDialog()) {
            try {
                imprimer.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        } 
    }//GEN-LAST:event_jButtonImprimerActionPerformed
    private BufferedImage rotateImage(Image image, int angle) throws IOException {
        if (ImageBrain.getIcon() == null) {
            JOptionPane.showMessageDialog(this, "Aucune image chargée dans le JLabel.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        // Créer une BufferedImage à partir de l'image
        BufferedImage originalImage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_ARGB);

        // Dessiner l'image sur la BufferedImage
        Graphics2D g2d = originalImage.createGraphics();
        g2d.drawImage(image, 0, 0, null);
        g2d.dispose();

        // Afficher les dimensions de l'image originale
        System.out.println("Dimensions de l'image originale : " + originalImage.getWidth() + "x" + originalImage.getHeight());

        // Créer une nouvelle image pour contenir l'image pivotée
        BufferedImage rotatedImage = new BufferedImage(originalImage.getWidth(), originalImage.getHeight(), BufferedImage.TYPE_INT_ARGB);

        // Rotation de l'image
        g2d = rotatedImage.createGraphics();
        g2d.rotate(Math.toRadians(angle), rotatedImage.getWidth() / 2, rotatedImage.getHeight() / 2);
        g2d.drawImage(originalImage, 0, 0, null);
        g2d.dispose();

        // Afficher les dimensions de l'image pivotée
        System.out.println("Dimensions de l'image pivotée : " + rotatedImage.getWidth() + "x" + rotatedImage.getHeight());

        return rotatedImage;

    }

    private BufferedImage loadImage(String path) {
        try {
            // Charger l'image depuis les ressources du package
            InputStream inputStream = getClass().getResourceAsStream(path);
            if (inputStream == null) {
                JOptionPane.showMessageDialog(this, "Impossible de charger l'image.", "Erreur", JOptionPane.ERROR_MESSAGE);
                return null;
            }
            BufferedImage image = ImageIO.read(inputStream);
            inputStream.close(); // Fermer le flux après utilisation
            return image;
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    private BufferedImage adjustContrast(BufferedImage image, double contrast) {
        // Créer une copie de l'image originale pour appliquer l'ajustement de contraste
        BufferedImage adjustedImage = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_BYTE_GRAY);

        // Appliquer l'ajustement de contraste pixel par pixel
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                // Obtenir la valeur du niveau de gris du pixel
                int grayValue = image.getRaster().getSample(x, y, 0);

                // Appliquer l'ajustement de contraste à la valeur du niveau de gris
                int adjustedGrayValue = (int) (grayValue * contrast);

                // Vérifier les limites des valeurs de gris (0-255)
                adjustedGrayValue = Math.min(Math.max(adjustedGrayValue, 0), 255);

                // Définir la nouvelle valeur du niveau de gris dans l'image ajustée
                adjustedImage.getRaster().setSample(x, y, 0, adjustedGrayValue);
            }
        }
        return adjustedImage;
    }

    private BufferedImage inversionNiveauGris(BufferedImage image) {
        // Créer une copie de l'image originale pour inverser le niveau de gris
        BufferedImage invertedImage = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_BYTE_GRAY);

        // Inverser le niveau de gris pixel par pixel (soustraction de la valeur de gris des pixels à la valeur maximal de profondeur des pixels)
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                // Obtenir la valeur du niveau de gris du pixel
                int grayValue = image.getRaster().getSample(x, y, 0);

                // Inverser le niveau de gris en soustrayant de la valeur maximale possible
                int invertedGrayValue = 255 - grayValue;

                // Définir la nouvelle valeur du niveau de gris dans l'image inversée
                invertedImage.getRaster().setSample(x, y, 0, invertedGrayValue);
            }
        }
        return invertedImage;
    }
            // Fermer la fenêtre actuelle
            dispose();

    // Méthode pour flipper horizontalement l'image de la base de données
    private void flipHImage() {
        if (imageData != null) {
            
            if (imageFromDB == null) {
                
            }
            if (imageFromDB != null) {
                AffineTransform tx = AffineTransform.getScaleInstance(1, -1);
                tx.translate(0, -imageFromDB.getHeight());
                AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_NEAREST_NEIGHBOR);
                BufferedImage flippedImage = op.filter(imageFromDB, null);
                // Mettre à jour l'image originale
                imageFromDB = flippedImage;
                // Afficher l'image retournée
                applyProcessing(flippedImage);
                
            } else {
                System.out.println("Impossible de charger l'image depuis les données de la base de données.");
            }
        } else {
            System.out.println("Aucune donnée d'image disponible depuis la base de données.");
        }
    }

// Méthode pour flipper verticalement l'image de la base de données
    private void flipVImage() {
        if (imageData != null) {
            //BufferedImage imageFromDB = loadImageFromBytes(imageData);
            if (imageFromDB == null) {
                
            }
            if (imageFromDB != null) {
                AffineTransform tx = AffineTransform.getScaleInstance(-1, 1);
                tx.translate(-imageFromDB.getWidth(), 0);
                AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_NEAREST_NEIGHBOR);
                BufferedImage flippedImage = op.filter(imageFromDB, null);
                // Mettre à jour l'image originale
                imageFromDB = flippedImage;
                // Afficher l'image retournée
                applyProcessing(flippedImage);
            } else {
                System.out.println("Impossible de charger l'image depuis les données de la base de données.");
            }
        } else {
            System.out.println("Aucune donnée d'image disponible depuis la base de données.");
        }
    }

    public JLabel getImageBrain() {
        return ImageBrain;
        if (imageData != null) {
            //BufferedImage imageFromDB = loadImageFromBytes(imageData);
            if (imageFromDB != null) {
                try {
                    // Rotation de l'image
                    BufferedImage rotatedImage = rotateImage(imageFromDB, 90 * (++rotationAngle));
                    // Mise à jour de l'image actuelle dans le JLabel
                    applyProcessing(rotatedImage);
                    imageFromDB = rotatedImage;
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            } else {
                System.out.println("Impossible de charger l'image depuis la base de données.");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DMR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageBrain;
    private javax.swing.JLabel acte;
    private javax.swing.JLabel infoAdresse;
    private javax.swing.JLabel infoCode;
    private javax.swing.JLabel infoDate;
    private javax.swing.JLabel infoID;
    private javax.swing.JLabel infoPrenom;
    private javax.swing.JButton jButtonDecreaseContrast;
    private javax.swing.JButton jButtonEnregistrerCR;
    private javax.swing.JButton jButtonFlipH;
    private javax.swing.JButton jButtonFlipV;
    private javax.swing.JButton jButtonImprimer;
    private javax.swing.JButton jButtonIncreaseContraste;
    private javax.swing.JButton jButtonInversionGris;
    private javax.swing.JButton jButtonRestartContrast;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonRotate90;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCR;
    private javax.swing.JPanel jPanelInfoActe;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCR;
    // End of variables declaration//GEN-END:variables

    

    private void afficherCompteRendu(int idCRint) {
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@im2ag-oracle.univ-grenoble-alpes.fr:1521:im2ag", "qezbourn", "d87b488b99");
            String sql = "SELECT CONTENU FROM CR WHERE IDCR = ?";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setInt(1, idCRint);
            ResultSet resultSet = statement.executeQuery();

            StringBuilder contentBuilder = new StringBuilder();
            while (resultSet.next()) {
                String contenu = resultSet.getString("CONTENU");
                contentBuilder.append(contenu).append("\n");
                System.out.println("idpatient :" + idPatient + "-");
                System.out.println("texte CR: " + contenu + "-");
                System.out.println("idCRint: " + idCRint + "-");
            }

            String contenuCR = contentBuilder.toString();
            //   if (jTextAreaCR.getClickCount() == 2) { // Double clic sur une ligne 
            if (contenuCR.isEmpty()) { // si il y a déja un contenu on n'a pas le droit de le modifier 
                jTextAreaCR.setEditable(true); // Autoriser la modification si le contenu est vide
            } else {
                jTextAreaCR.setText(contenuCR); // Mettre à jour le texte du jTextAreaCR avec le contenu du compte rendu
                jTextAreaCR.setEditable(false); // Bloquer la modification si le contenu est déjà présent
                this.jButtonEnregistrerCR.setVisible(false);// Masquer le bouton pour ajouter le CR
                JOptionPane.showMessageDialog(null, "Le compte rendu ne peut pas être modifié car il contient déjà du texte.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erreur lors de la récupération du compte rendu : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
}
