/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import testjdbc.TestConnexionEtRequetes;

/**
 *
 * @author alana
 */
public class ConnexionVerifie extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ConnexionVerifie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextIdd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextIdd1 = new javax.swing.JTextField();
        JTextMOTDEPASSE = new javax.swing.JPasswordField();
        jLabelIdd = new javax.swing.JLabel();
        jLabelMdp = new javax.swing.JLabel();
        connexion = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/house-princeton-plainsboro-brand-a-transparent.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenue sur votre espace de connexion");

        jTextIdd.setFont(new java.awt.Font("Galvji", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/house-princeton-plainsboro-brand-a-transparent.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        jLabel4.setText("Bienvenue sur votre espace de connexion");

        jTextIdd1.setFont(new java.awt.Font("Galvji", 0, 14)); // NOI18N

        JTextMOTDEPASSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextMOTDEPASSEActionPerformed(evt);
            }
        });

        jLabelIdd.setFont(new java.awt.Font("Galvji", 0, 14)); // NOI18N
        jLabelIdd.setText("Identifiant");

        jLabelMdp.setFont(new java.awt.Font("Galvji", 0, 14)); // NOI18N
        jLabelMdp.setText("Mot de passe");

        connexion.setText("jButton1");
        connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelIdd)
                            .addComponent(jLabelMdp))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTextMOTDEPASSE, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jTextIdd1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(connexion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextIdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelIdd))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTextMOTDEPASSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMdp)))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(connexion)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextMOTDEPASSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextMOTDEPASSEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextMOTDEPASSEActionPerformed

    private void connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionActionPerformed
        Connection conn = null;
        String dbUrl = "jdbc:oracle:thin:@im2ag-oracle.univ-grenoble-alpes.fr:1521:im2ag";//se connecter à oracle 
        String jdbcDriver = "oracle.jdbc.driver.OracleDriver";//se connecter à notre BD`

        try {
            Class.forName(jdbcDriver);//pour charger le driver 
            DriverManager.setLoginTimeout(4);//temps max de chargement 4 sec
            conn = DriverManager.getConnection(dbUrl, "qezbourn", "d87b488b99");//pour se connecter à la BD
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TestConnexionEtRequetes.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {


        }
        if (conn != null) {
            System.out.println("Connexion établie");

            try {
                Statement st;
                try {
                    st = conn.createStatement();
                    String query = "SELECT ID FROM Personnel";
                    ResultSet rs = st.executeQuery(query);
                    while (rs.next()) {
                        String ID = rs.getString("ID");
                        System.out.println("test = " + ID);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ConnexionVerifie.class.getName()).log(Level.SEVERE, null, ex);
                }

//            String ID = rs.getString("ID");
//            System.out.println(ID);
//
//            if (IDSaisi.equals(ID)) { //&& MDPSaisi.equals("abc")
//                //Ouverture d'une nouvelle page d'accueil Medecin
//                System.out.println("connexion medecin possible");
//                Acceuil nouveauJFrame = new Acceuil();
//                nouveauJFrame.setVisible(true);
//                dispose();
//
//               
//                }
                // } catch (SQLException ex) {
                //  Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);

//            String ID = rs.getString("ID");
//            System.out.println(ID);
//
//            if (IDSaisi.equals(ID)) { //&& MDPSaisi.equals("abc")
//                //Ouverture d'une nouvelle page d'accueil Medecin
//                System.out.println("connexion medecin possible");
//                Acceuil nouveauJFrame = new Acceuil();
//                nouveauJFrame.setVisible(true);
//                dispose();
//
//               
//                }
                // } catch (SQLException ex) {
                //  Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
            } finally {

                try {
                    Statement st = conn.createStatement();
                    if (st != null) {
                        st.close();
                    }
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ConnexionVerifie.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            System.out.println("connexion impossible");
//            JOptionPane.showMessageDialog(Connexion.this,
//                    "Identifiant ou mot de passe invalide",
//                    "Erreur de connexion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_connexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnexionVerifie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnexionVerifie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnexionVerifie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnexionVerifie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnexionVerifie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JTextMOTDEPASSE;
    private javax.swing.JButton connexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelIdd;
    private javax.swing.JLabel jLabelMdp;
    private javax.swing.JTextField jTextIdd;
    private javax.swing.JTextField jTextIdd1;
    // End of variables declaration//GEN-END:variables
}
